# Generated by Django 5.1.5 on 2025-01-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_id', models.UUIDField(blank=True, default='8zF8U3jGBvvEq9nT2CNFc2', editable=False, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_num', models.IntegerField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('join_date_at', models.DateTimeField(auto_now_add=True)),
                ('agent_id', models.BigIntegerField(null=True)),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
