# Generated by Django 5.1.5 on 2025-01-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='buyer_id',
            field=models.UUIDField(blank=True, default='XiuQRMDP4EYeC5fEMyPx5t', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
