# Generated by Django 5.1.5 on 2025-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_module', '0002_alter_buyers_buyer_id_alter_buyers_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='buyer_id',
            field=models.UUIDField(blank=True, default='yGesZwcudqYiPAmzW8V289', editable=False, null=True),
        ),
    ]
