# Generated by Django 5.1.5 on 2025-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_module', '0003_alter_buyers_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='buyer_id',
            field=models.UUIDField(blank=True, default='6hcb29gcKxfWdo8oWJrQxF', editable=False, null=True),
        ),
    ]
