# Generated by Django 5.1.5 on 2025-01-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer_module', '0004_alter_buyers_buyer_id'),
        ('seller_module', '0003_alter_sellers_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_id', models.UUIDField(blank=True, default='u9cUqfEP3nymvVUogBQARk', editable=False, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('join_date_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('investor_id', models.BigIntegerField(null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer_module.buyers')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller_module.sellers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
