# Generated by Django 5.1.5 on 2025-01-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='agent_id',
            field=models.UUIDField(blank=True, default='K3xk8VWBdSnNNtgB3Pm4Zr', editable=False, null=True),
        ),
    ]
