# Generated by Django 5.1.5 on 2025-01-19 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_module', '0003_alter_buyers_buyer_id'),
        ('seller_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_id', models.UUIDField(blank=True, default='QFdCeDZvAzx5f7DX7M2arC', editable=False, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('agent_id', models.BigIntegerField(null=True)),
                ('investor_id', models.BigIntegerField(null=True)),
                ('property_id', models.BigIntegerField(null=True)),
                ('agent_rep', models.CharField(max_length=50, null=True)),
                ('bac', models.BooleanField(default=False)),
                ('bac_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_agreement', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer_module.buyers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Sellars',
        ),
    ]
