# Generated by Django 5.1.5 on 2025-01-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_module', '0002_sellers_delete_sellars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='seller_id',
            field=models.UUIDField(blank=True, default='dyLP2AqCzkvrvwFHvu8Wav', editable=False, null=True),
        ),
    ]
