# Generated by Django 5.1.5 on 2025-01-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_module', '0002_alter_agents_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverstors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_id', models.UUIDField(blank=True, default='TFysCPMALW3DPu9FZ8ihuR', editable=False, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('join_date_at', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent_module.agents')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
