# .github/workflows/ci.yml

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl "https://api.render.com/deploy/srv-cvsvso95pdvs739d634g?key=BzYC-5dmnUE"